// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePIfjymy6XmqGFPcMlWMFAusGnDL7eqI',
    appId: '1:216239142868:web:bf514ca3a4573297a44841',
    messagingSenderId: '216239142868',
    projectId: 'flutter-25mob',
    authDomain: 'flutter-25mob.firebaseapp.com',
    storageBucket: 'flutter-25mob.appspot.com',
    measurementId: 'G-DNX8G4NXBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG6r17NyClTNKi49GHADnQI1i-DlXmy4o',
    appId: '1:216239142868:android:19132f2c85f17494a44841',
    messagingSenderId: '216239142868',
    projectId: 'flutter-25mob',
    storageBucket: 'flutter-25mob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo8p5sOC0UAAymg4f1MomRKyZLnRWKcBY',
    appId: '1:216239142868:ios:af49bbd9e3b2ac20a44841',
    messagingSenderId: '216239142868',
    projectId: 'flutter-25mob',
    storageBucket: 'flutter-25mob.appspot.com',
    iosClientId: '216239142868-iiogva57a9uovp0mgggdfgajv1ajbo5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameWikiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo8p5sOC0UAAymg4f1MomRKyZLnRWKcBY',
    appId: '1:216239142868:ios:af49bbd9e3b2ac20a44841',
    messagingSenderId: '216239142868',
    projectId: 'flutter-25mob',
    storageBucket: 'flutter-25mob.appspot.com',
    iosClientId: '216239142868-iiogva57a9uovp0mgggdfgajv1ajbo5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameWikiApp',
  );
}
